version: '3.4'
networks:
  demoblooddonorapp:
services:
  blooddonorapigateway:
    container_name: demo-blood-donor
    image: ${DOCKER_REGISTRY-}blooddonorapigateway
    build:
      context: .
      dockerfile: BloodDonorAPI\Dockerfile
    ports:
      - 5101:80
    depends_on:
      - demoappdb
    environment:
      - DB_HOST=demoappdb
      - DB_NAME=BloodDonorDB
      - DB_SA_PASSWORD=Blooddonor123*
    networks:
      - demoblooddonorapp

  swagger:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui:v3.54.0
    ports:
      - "5101:8080"
    environment:
      - SWAGGER_JSON=/openapi/openapi.json
    volumes:
      - ./openapi:/openapi
    networks:
      - demoblooddonorapp